# Generated by Django 5.2.1 on 2025-05-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=250)),
                ("model", models.CharField(max_length=250)),
                ("color", models.CharField(max_length=30)),
                ("engin", models.CharField(max_length=30)),
                ("year", models.IntegerField(default=1980)),
                ("image", models.ImageField(blank=True, upload_to="carimages/")),
            ],
        ),
    ]
