# Generated by Django 5.2.1 on 2025-05-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
