# Generated by Django 5.2.1 on 2025-05-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_name", models.CharField(max_length=250)),
                ("cuisine", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True)),
                ("rating", models.FloatField(blank=True)),
                ("price", models.IntegerField(blank=True)),
                ("street", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=10)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("phone", models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
