# Generated by Django 5.2.1 on 2025-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="site_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="rating",
            field=models.FloatField(blank=True, max_length=5),
        ),
    ]
